botika/yarte

yarte_derive/src/generator/mod.rs, yarte_derive/src/generator/visit_derive.rs, yarte_derive/src/generator/visits.rs, yarte_helpers/src/helpers/markup.rs
Improve performance at render variables detecting wrapped by type and circumstance. Remove inline attributes working better at big_table bench
=> Improve render

benches/src/fmt.rs, example/build.rs, example/src/main.rs, example/templates/body.hbs, example/templates/index.hbs, yarte_derive/src/generator/mod.rs, yarte_derive/src/generator/visit_derive.rs
Add derive attribute `err`. It's only available when feature actix-web is enabled.
=> Add error response  body attribute with actix-web 

example/README.md, yarte/tests/eval.rs, yarte_derive/Cargo.toml, yarte_derive/src/codegen/html.rs, yarte_derive/src/codegen/mod.rs, yarte_derive/src/codegen/text.rs, yarte_derive/src/generator/identifier.rs, yarte_derive/src/generator/mod.rs, yarte_derive/src/generator/scope.rs, yarte_derive/src/generator/validator.rs, yarte_derive/src/generator/visit_derive.rs, yarte_derive/src/generator/visit_each.rs, yarte_derive/src/generator/visit_partial.rs, yarte_derive/src/generator/visits.rs, yarte_derive/src/lib.rs, yarte_derive/src/logger.rs
=> Add HIR, move to TokenStream and split codegen

.travis.yml, Cargo.toml, yarte_wasm_app/Cargo.toml, yarte_wasm_app/README.md, yarte_wasm_app/src/lib.rs
=> Add yarte wasm application

.travis.yml, Cargo.toml, yarte_wasm_app/Cargo.toml, yarte_wasm_app/src/lib.rs
=> Fix wasm app for run in rust stable

Cargo.toml, example_wasm/client/Cargo.toml, example_wasm/client/src/lib.rs, example_wasm/client/yarte.toml, example_wasm/server/Cargo.toml, example_wasm/server/src/main.rs, example_wasm/server/yarte.toml, example_wasm/templates/fortune.hbs, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/wasm.rs, yarte_codegen/src/lib.rs, yarte_codegen/src/wasm/client/each.rs, yarte_codegen/src/wasm/client/mod.rs, yarte_dom/src/dom_fmt.rs, yarte_template/Cargo.toml, yarte_template/src/lib.rs
=> Add first render example

yarte/tests/resolve.rs, yarte_hir/src/lib.rs, yarte_hir/src/visit_each.rs, yarte_html/src/interface.rs, yarte_html/src/tree_builder/mod.rs, yarte_parser/src/lib.rs
=> Add resolve expression

yarte/templates/partial-block.hbs, yarte/templates/with-partial-block.hbs, yarte/tests/partial.rs, yarte_hir/src/lib.rs, yarte_hir/src/visit_each.rs, yarte_parser/src/lib.rs, yarte_parser/src/pre_partials.rs, yarte_parser/src/strnom.rs, yarte_parser/src/test.rs
=> Add partial-block

example_wasm/templates/fortune.hbs, yarte/templates/html/fortune.hbs, yarte/tests/html.rs, yarte/tests/wasm.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/lib.rs, yarte_codegen/src/macros.rs, yarte_codegen/src/wasm/client/each.rs, yarte_codegen/src/wasm/client/events.rs, yarte_codegen/src/wasm/client/messages.rs, yarte_codegen/src/wasm/client/mod.rs, yarte_codegen/src/wasm/client/test.rs, yarte_dom/src/dom_fmt.rs
=> Prettify client codegen

yarte_html/Cargo.toml, yarte_parser/Cargo.toml, yarte_parser/src/error.rs, yarte_parser/src/lib.rs, yarte_parser/src/source_map.rs, yarte_parser/src/strnom.rs, yarte_parser/src/test.rs
#39 
Depend https://github.com/rust-lang/annotate-snippets-rs/pull/33
=> Update annotate_snippets to git version

yarte_codegen/Cargo.toml, yarte_codegen/src/lib.rs, yarte_derive/Cargo.toml, yarte_derive/src/lib.rs, yarte_dom/Cargo.toml, yarte_dom/src/lib.rs, yarte_hir/Cargo.toml, yarte_hir/src/lib.rs, yarte_parser/Cargo.toml, yarte_parser/src/lib.rs
=> Get span at proc_macro context

book/src/templating/compile-error.md, yarte/tests/basic.rs, yarte/tests/fails/user-compile-error.rs, yarte/tests/fails/user-compile-error.stderr, yarte_hir/src/error.rs, yarte_hir/src/lib.rs, yarte_hir/src/validator.rs, yarte_parser/src/lib.rs, yarte_parser/src/test.rs
=> Add at compile time user errors

book/src/SUMMARY.md, book/src/meta-programming.md, yarte/tests/basic.rs, yarte/tests/eval.rs, yarte/tests/partial.rs
=> Improve documentation

.gitignore, book/book.toml, book/src/meta-programming.md, yarte/Cargo.toml, yarte/tests/eval.rs, yarte_codegen/Cargo.toml, yarte_derive/Cargo.toml, yarte_dom/Cargo.toml, yarte_format/Cargo.toml, yarte_helpers/Cargo.toml, yarte_hir/Cargo.toml, yarte_hir/src/lib.rs, yarte_html/Cargo.toml, yarte_parser/Cargo.toml, yarte_wasm_app/Cargo.toml
=> Update v_eval to 0.5

yarte/tests/partial.rs, yarte_hir/src/lib.rs, yarte_hir/src/scope.rs, yarte_hir/src/visit_derive.rs, yarte_hir/src/visit_each.rs, yarte_hir/src/visits.rs, yarte_parser/src/lib.rs, yarte_parser/src/strnom.rs
Provisional solution while work in refactor lowering ast
Closes #121
=> Reduce default recursion to 128

yarte/tests/issues.rs, yarte_helpers/Cargo.toml, yarte_helpers/src/helpers/markup.rs, yarte_hir/Cargo.toml
=> Add escape char

.github/workflows/bench.yml, benches/Cargo.toml, benches/src/all.rs, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/basic.rs, yarte/tests/fixed.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/fixed.rs, yarte_codegen/src/lib.rs, yarte_derive/Cargo.toml, yarte_derive/src/lib.rs, yarte_helpers/Cargo.toml, yarte_helpers/src/helpers/fixed.rs, yarte_helpers/src/helpers/mod.rs, yarte_helpers/src/lib.rs, yarte_hir/Cargo.toml
=> Write to fixed allocation

yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/at_helpers.rs, yarte_helpers/Cargo.toml, yarte_helpers/src/at_helpers.rs, yarte_helpers/src/helpers/fixed.rs, yarte_helpers/src/helpers/markup.rs, yarte_helpers/src/helpers/mod.rs, yarte_helpers/src/lib.rs, yarte_hir/src/lib.rs
=> Fix json and fixed features conflict

benches/Cargo.toml, benches/src/all.rs, example/Cargo.toml, example/src/main.rs, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/at_helpers.rs, yarte/tests/benchs.rs, yarte/tests/bytes.rs, yarte/tests/fixed.rs, yarte/tests/wrapped.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/bytes.rs, yarte_codegen/src/fixed.rs, yarte_codegen/src/fmt.rs, yarte_codegen/src/fn_fmt.rs, yarte_codegen/src/html.rs, yarte_codegen/src/lib.rs, yarte_codegen/src/text.rs, yarte_derive/Cargo.toml, yarte_derive/src/lib.rs, yarte_format/src/lib.rs, yarte_helpers/src/helpers/fixed.rs, yarte_helpers/src/helpers/markup.rs, yarte_helpers/src/helpers/memcpy.rs, yarte_helpers/src/helpers/mod.rs
=> Use MaybeUninit type and add bytes crate support

.travis.yml, benches/Cargo.toml, benches/src/all.rs, example/Cargo.toml, example/src/main.rs, example/templates/index_bytes.hbs, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/benchs.rs, yarte/tests/bytes.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/bytes.rs, yarte_codegen/src/lib.rs, yarte_derive/Cargo.toml, yarte_derive/src/lib.rs, yarte_helpers/Cargo.toml, yarte_helpers/src/helpers/bytes.rs, yarte_helpers/src/helpers/fixed.rs, yarte_helpers/src/helpers/mod.rs, yarte_hir/Cargo.toml
Add realloc logic and move to infallible return
=> Refactor TemplateBytesTrait

example/yarte.toml, yarte_derive/Cargo.toml, yarte_derive/src/logger.rs
=> Remove prettyprint in favor of bat

.travis.yml, yarte/src/lib.rs, yarte_helpers/Cargo.toml, yarte_helpers/src/helpers/bytes.rs, yarte_helpers/src/helpers/mod.rs, yarte_helpers/src/helpers/ryu.rs, yarte_helpers/src/helpers/ser_json.rs, yarte_helpers/tests/json.rs
Serialize json with same methods that yarte
Closes #150
=> Serializer json

yarte/src/lib.rs, yarte/tests/bytes.rs, yarte_codegen/src/bytes.rs, yarte_codegen/src/wasm/mod.rs, yarte_codegen/src/write_b.rs, yarte_derive/src/lib.rs
=> Add 3 bytes write byte-by-byte

example_wasm/client/src/lib.rs, yarte_codegen/src/wasm/client/events.rs, yarte_codegen/src/wasm/client/mod.rs, yarte_codegen/src/wasm/client/tests/each.rs, yarte_codegen/src/wasm/client/tests/mod.rs, yarte_codegen/src/wasm/client/tests/tree_diff.rs, yarte_wasm_app/benches/src/app.rs, yarte_wasm_app/benches/src/lib.rs, yarte_wasm_app/src/lib.rs, yarte_wasm_app/src/queue.rs, yarte_wasm_app/tests/lib.rs
Use singleton pattern for `Addr<A: App>`
#37
=> Wasm App singleton

examples/raytrace-parallel/.gitignore, examples/raytrace-parallel/Cargo.toml, examples/raytrace-parallel/README.md, examples/raytrace-parallel/build.sh, examples/raytrace-parallel/client/Cargo.toml, examples/raytrace-parallel/client/src/app.rs, examples/raytrace-parallel/client/src/handler.rs, examples/raytrace-parallel/client/src/lib.rs, examples/raytrace-parallel/client/src/scene.rs, examples/raytrace-parallel/index.html, examples/raytrace-parallel/index.js, examples/raytrace-parallel/server.py, examples/raytrace-parallel/utils/Cargo.toml, examples/raytrace-parallel/utils/src/lib.rs, examples/raytrace-parallel/worker-pool/Cargo.toml, examples/raytrace-parallel/worker-pool/src/lib.rs, examples/raytrace-parallel/worker.js
=> Example parallel raytracing in wasm

yarte_lexer/gencode/src/lib.rs, yarte_lexer/src/expr_list.rs, yarte_lexer/src/expr_pipe.rs, yarte_lexer/src/lib.rs, yarte_lexer/src/parse.rs, yarte_lexer/src/source_map.rs, yarte_lexer/src/stmt_local.rs, yarte_lexer/src/strnom.rs, yarte_lexer/tests/fixtures.rs
Refactor pipes overwrite pipes behaviour
=> Improve strnom

.travis.yml, benches/Cargo.toml, benches/src/all.rs, book/book.toml, examples/fortune/Cargo.toml, examples/fortune/src/main.rs, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/at_helpers.rs, yarte/tests/benchs.rs, yarte/tests/bytes.rs, yarte/tests/example.rs, yarte/tests/json.rs, yarte/tests/wasm.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/wasm/client/mod.rs, yarte_derive/Cargo.toml, yarte_derive/src/ser_json.rs, yarte_dom/Cargo.toml, yarte_helpers/Cargo.toml, yarte_hir/Cargo.toml, yarte_html/Cargo.toml, yarte_html/src/lib.rs, yarte_html/src/tree_builder/mod.rs, yarte_parser/Cargo.toml
Update `buf-min` version to `0.4`
=> Minor change to keep the mouths shut

.travis.yml, book/book.toml, yarte/Cargo.toml, yarte/src/lib.rs, yarte/tests/bytes.rs, yarte/tests/json.rs, yarte/tests/ywrite.rs, yarte_codegen/Cargo.toml, yarte_codegen/src/bytes.rs, yarte_derive/Cargo.toml, yarte_derive/src/ser_json.rs, yarte_dom/Cargo.toml, yarte_helpers/Cargo.toml, yarte_helpers/src/helpers/bytes.rs, yarte_helpers/src/helpers/ser_json/mod.rs, yarte_hir/Cargo.toml, yarte_html/Cargo.toml, yarte_parser/Cargo.toml
=> Update Buf-min to 0.5.0

book/src/config.md, book/src/description.md, book/src/getting_started.md, book/src/templating/helpers/conditional.md, book/src/templating/helpers/helpers.md, book/src/templating/partial.md, book/src/templating/rust_code.md, book/src/templating/templating.md
=> Fix yarte book

yarte_lexer/src/error.rs, yarte_lexer/src/expr_list.rs, yarte_lexer/src/expr_pipe.rs, yarte_lexer/src/lib.rs, yarte_lexer/src/parse.rs, yarte_lexer/src/source_map.rs, yarte_lexer/src/stmt_local.rs, yarte_lexer/src/strnom.rs, yarte_lexer/tests/fixtures.rs
=> Add structure for use sink at lexer

.github/workflows/linux.yml, .travis.yml, yarte/templates/issues/issue-224.hbs, yarte/templates/issues/issue-224.txt, yarte/tests/issues.rs
=> Coverage for #224
